name: Build OCR Console App
on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore NuGet packages
      run: msbuild .\FoundryOcr.Cli.csproj -t:Restore -p:Configuration=Release

    - name: Build the application
      run: msbuild .\FoundryOcr.Cli.csproj -p:Configuration=Release -p:Platform=x64 -p:WindowsAppSDKSelfContained=true

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: ocr-tool
        path: bin\x64\Release\net8.0-windows10.0.22621.0\win-x64\publish\
